name: "cleanup-cache"

on:
  schedule:
    # 每周日清理一次缓存
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup old caches
        uses: actions/github-script@v7
        with:
          script: |
            const { data: caches } = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100
            });

            console.log(`Found ${caches.actions_caches.length} caches`);

            // 按创建时间排序，保留最新的15个缓存
            const sortedCaches = caches.actions_caches
              .sort((a, b) => new Date(b.created_at) - new Date(a.created_at));

            const cachesToKeep = sortedCaches.slice(0, 15);
            const cachesToDelete = sortedCaches.slice(15);

            console.log(`Keeping ${cachesToKeep.length} caches`);
            console.log(`Deleting ${cachesToDelete.length} caches`);

            for (const cache of cachesToDelete) {
              try {
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id
                });
                console.log(`✓ Deleted cache: ${cache.key} (${(cache.size_in_bytes / 1024 / 1024).toFixed(2)} MB)`);
              } catch (error) {
                console.log(`✗ Failed to delete cache ${cache.key}: ${error.message}`);
              }
            }

            // 显示剩余缓存大小
            const remainingSize = cachesToKeep.reduce((sum, cache) => sum + cache.size_in_bytes, 0);
            console.log(`Remaining cache size: ${(remainingSize / 1024 / 1024 / 1024).toFixed(2)} GB`);
